package com.przychodnia.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DBManager {
	
	private Connection connection;
	private Statement stmt;
	
	public DBManager() throws SQLException {
				
			connection = DriverManager.getConnection("jdbc:hsqldb:mem:localhost/przychodnia");	
			stmt=connection.createStatement();
			
			ResultSet result = connection.getMetaData().getTables(null, null, null, null);
			boolean lekarze = false;
			boolean pacjenci = false;
			while(result.next()){
				String name = result.getString("TABLE_NAME");
				if(name.equals("lekarze")){
					lekarze=true;
				}else if(name.equals("pacjenci")){
					pacjenci=true;
				}
			}
			if(!lekarze){
				System.out.println("Tworzenie tabeli lekarzy");
				stmt.executeUpdate("" +
						"CREATE TABLE lekarze(" +
						"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
						"imie varchar(30)," +
						"nazwisko varchar(30)," +
						"specjalizacja varchar(30))");
			}
			if(!pacjenci){
				System.out.println("Tworzenie tabeli pacjentow");
				stmt.executeUpdate("" +
						"CREATE TABLE pacjenci(" +
						"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
						"imie varchar(30)," +
						"nazwisko varchar(30)," +
						"wiek int," +
						"lekarz_id bigint, "+
						"FOREIGN KEY (lekarz_id) REFERENCES lekarze(id))");
									
			}
	}
	

	public Connection getConnection() {
		return connection;
	}
		
	

}
